// THIS FILE IS FOR TESTING CODEQL SECRET SCANNING ONLY
// Remove after verifying alerts work

const API_KEY = "AKIAIOSFODNN7EXAMPLE";
const SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";
const DB_PASSWORD = "SuperSecret123!";
const TOKEN = "ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef12";
